export const CATEGORY_ACTION_TYPES = {
    // SET_CATEGORIES: 'SET_CATEGORIES',
    FETCH_CATEGORIE_START: 'fetch/FETCH_CATEGORIES_START',
    FETCH_CATEGORIE_SUCCESS: 'fetch/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIE_FAILED: 'fetch/FETCH_CATEGORIES_FAILED',
}